runtime: go113
service: mac-oui

automatic_scaling:
    max_concurrent_requests: 75
    min_pending_latency: 100ms
    max_pending_latency: 200ms

handlers:
- url: /favicon.ico
  static_files: resources/static/favicon.ico
  upload: resources/static/favicon.ico
- url: /.*
  script: auto

inbound_services:
- warmup
